# shso basic
#
# import mysql.connector
import time
import datetime

def init():
	global db 
	global cmdMap
	global srvVer
	global validCliVer

	srvVer = "00.00.017"
	validCliVer = ["18.4", "18.5"]
	cmdMap = {"ping": handlePing, "keepAlive": handleKeepAlive }
	
	db = _server.getDatabaseManager()


def destroy():
	_server.trace( "Python extension dying" )


def escapeQuotes(string):
	string2 = str(string).replace( '"', '\"')
	string2 = string2.replace( "'", "\'")
	string2 = string2.replace("\\", "\\\\")
	return string2


def handleRequest(cmd, params, who, roomId, protocol):
	#if protocol == "xml":
	if cmdMap.has_key(cmd):
		cmdMap[cmd](params, who, roomId)
		

def handleInternalEvent(evt):
	chan = evt.getObject("chan")
	# nick = "chumbawumbA"
	nick = evt.getParam("nick")
	passw = evt.getParam("pass")
	cliVer = None
	# Get the secret key of this channel
	key = _server.getSecretKey(chan)
	_server.trace("key = " + str(key))

	#_server.trace("evt = " + ' '.join(map(str, dir(evt))) )
	evtName = evt.getEventName()
	_server.trace( "Received internal event: " + evt.getEventName() )
	if evtName == "loginRequest":
		#### special case if user nick starts with 'version=', we do a client/server version validation.  #######
		importantInfo = nick.split(',')	
		if len(importantInfo) > 1:
			nick = importantInfo[0]
			cliVer = importantInfo[1]
			if len(importantInfo) > 2:
				md5hash = importantInfo[2]
			debugFlags = 0
			if len(importantInfo) > 3:
				debugFlags = importantInfo[3]
			_server.trace("attempting client/server version validation!")
			_server.trace("cliVer=" + cliVer)
			_server.trace("nick=" + escapeQuotes(nick))
			
			#if client version isnt what is expected, do the following:
			valid = False
			_server.trace(cliVer)
			if (cliVer in validCliVer):
				valid = True

			if valid == False:
				user = _server.getUserByChannel(chan)

				response = {}
				response["_cmd"] = "logKO"
				response["err"] = "Invalid client version"
				response["status"] = 403
				_server.sendResponse(response, -1, None, chan)
				#_server.disconnectUser(user)  # disconnect client if version does not validate.
				return
		else:
			response = {}
			response["_cmd"] = "logKO"
			response["err"] = "Wrong client , use launcher to check for updates"
			response["status"] = 403
			_server.sendResponse(response, -1, None, chan)
			return

		#########################################################################################	
	
		error = ""
		valid = 0
		response = {}
		user = None
		session_token = None
		queryRes = None
		checkSQL = "SELECT checkCreds('" + escapeQuotes(nick) + "', '" + escapeQuotes(passw) + "', '" + escapeQuotes(str(key)) + "') AS Result;"
		UserCheckQueryResult = db.executeQuery(checkSQL)
		if (UserCheckQueryResult) and (UserCheckQueryResult.size() > 0):
			result = UserCheckQueryResult.get(0).getItem("Result")
			_server.trace('User login request result: ' + str(result))
			if result != 'Authenticated':
				error = result
				failMsg = result
				response["_cmd"] = "logKO"
				response["err"] = failMsg
				response["status"] = 443
				_server.trace(failMsg)
			else:
				userInfoQuery = "SELECT * FROM user where username='" + escapeQuotes(nick) + "';"
				queryRes = db.executeQuery(userInfoQuery)
				row = queryRes.get(0)
				username = row.getItem("Username")
				display_name = row.getItem("Nick")
				playerID = row.getItem("ID")
				paid = row.getItem("Paid")
				dbpass = row.getItem("Password")
				# session_token = generate_token()
				gentoken = "SELECT UUID() AS token;"
				tokenQuery = db.executeQuery(gentoken)
				if (tokenQuery.size() > 0):
					for row in tokenQuery:
						session_token = str(row.getItem("token"))

				sql = "INSERT INTO tokens VALUES(" + escapeQuotes(str(playerID)) + ", '" + escapeQuotes(session_token) + "') ON DUPLICATE KEY UPDATE token='" + escapeQuotes(session_token) + "'"
				_server.trace(username)
				_server.trace(display_name)
				_server.trace(playerID)
				_server.trace(session_token)
				success = db.executeCommand(sql)
				if not success:
					error = "Record insertion failed."
					_server.trace('FAILED TO SAVE TOKEN!')
				else:
					_server.trace('SAVED NEW TOKEN SUCCESSFULLY!')
					response["_cmd"] = "logOK"
					if display_name is not None:
						obj = _server.loginUser(display_name, dbpass, chan)
					else:
						obj = _server.loginUser(nick, dbpass, chan)
						#if obj.success == true:
					_server.trace("Calling getUserByChannel()!")
					user = _server.getUserByChannel(chan)
					response["name"] = username
					# the ID returned HAS to be the userId generated by smartfox.
					response["id"] = str(user.getUserId())
					#response["id"] = ID 
					response["playerId"] = playerID
					response["paid"] = paid
					response["sessionToken"] = str(session_token)
					
					# now write login date
					ts = time.time()
					timestamp = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
					ip = user.getIpAddress()

					sql = "UPDATE shso.user SET LastLogin = '" + escapeQuotes(timestamp) + "'  WHERE username = '" + escapeQuotes(nick) + "'";
					success = db.executeCommand(sql)

		# elif valid == -1:
		# 	response["_cmd"] = "logKO"
		# 	response["err"] = failMsg
		# 	response["status"] = 443
		# 	_server.trace(failMsg)

		_server.trace("Calling sendResponse()!")
		_server.sendResponse(response, -1, None, chan)

		response = {}
		if error == "":
			_server.trace("Calling sendRoomList()!")
			_server.sendRoomList(user)
			_server.trace("Called sendRoomList()!")
			zone = _server.getCurrentZone()
			room = zone.getRoomByName("lobby")	
			_server.joinRoom(user,-1,True,room.getId(),"",False,True)
			response["_cmd"] = "notification_ready"
		else: 
			response["_cmd"] = "logKO"
		_server.sendResponse(response, -1, None, [user])
		if error == "":
			# Reconnect recovery: acknowledgements committed while this RTC
			# channel was unavailable must not remain stranded indefinitely.
			deliverPendingNotifications(user)




def handlePing(params, who, roomId):
	deliverPendingNotifications(who)
	response = {}
	response["_cmd"] = "ping"

	_server.sendResponse(response, -1, None, [who])
	
def handleKeepAlive(params, who, roomId):
	deliverPendingNotifications(who)
	response = {}
	response["_cmd"] = "keepAlive"

	_server.sendResponse(response, -1, None, [who])


def deliverPendingNotifications(who):
	# Purchases are committed by the HTTP service, while the shipped client
	# receives their completion on this separate notification connection.
	# Drain only this authenticated user's durable queue during the connection's
	# normal heartbeat; this avoids fabricating a completion in the client.
	account = db.executeQuery("SELECT ID FROM shso.user WHERE Nick='" + escapeQuotes(who.getName()) + "' OR Username='" + escapeQuotes(who.getName()) + "' LIMIT 1")
	if (account is None) or (account.size() == 0):
		return

	playerID = account.get(0).getItem("ID")
	pending = db.executeQuery("SELECT ID, MessageType, Guid, Success, ErrorCode, Balance FROM shso.pending_rtc_notifications WHERE Delivered=0 AND PlayerID=" + str(playerID) + " ORDER BY ID LIMIT 20")
	if pending is None:
		return

	for row in pending:
		response = {}
		response["_cmd"] = "notification"
		response["message_type"] = str(row.getItem("MessageType"))
		response["success"] = str(row.getItem("Success"))
		response["error_code"] = str(row.getItem("ErrorCode"))
		response["guid"] = str(row.getItem("Guid"))
		balance = row.getItem("Balance")
		if balance is not None:
			response["balance"] = str(balance)
		_server.sendResponse(response, -1, None, [who])
		db.executeCommand("UPDATE shso.pending_rtc_notifications SET Delivered=1 WHERE ID=" + str(row.getItem("ID")))
		_server.trace("Delivered " + response["message_type"] + " player=" + str(playerID) + " guid=" + response["guid"])
